name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
#     paths-ignore:
#       - '**.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build folders
        uses: actions/upload-artifact@v7
        with:
          name: build artifacts
          retention-days: 1
          path: |
            node/
            web/
            bundles/

  test:
    needs: build
    name: ${{ matrix.os }} with node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build artifacts
      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: test
        run: npm test
